TravelTripProject/Models/Sınıflar/Admin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class Admin
    {
        [Key]

        public int ID { get; set; }
        public string Kullanici { get; set; }
        public string Sifre { get; set; }
    }
}

TravelTripProject/Models/Sınıflar/AdresBlog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class AdresBlog
    {
        [Key]
        public  int ID { get; set; }
        public  string  Baslik{ get; set; }
        public  string  Aciklama{ get; set; }
        public  string  AdresAcik{ get; set; }
        public  string  Mail{ get; set; }
        public  string  Telefon{ get; set; }
        public  string  Konum{ get; set; }
    }
}

TravelTripProject/Models/Sınıflar/Anasayfa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class Anasayfa
    {
        [Key]
        public  int ID { get; set; }
        public string Baslik{ get; set; }
        public string Aciklama { get; set; }
       
    }
}

TravelTripProject/Models/Sınıflar/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class Blog
    {
        [Key]
        public  int ID { get; set; }
        public  string Baslik { get; set; }
        public  DateTime Tarih { get; set; }
        public  string Aciklama { get; set; }
        public  string BlogImage { get; set; }
        public ICollection<Yorumlar> Yorumlars  { get; set; }
    }
}

TravelTripProject/Models/Sınıflar/BlogYorum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class BlogYorum
    {
        public IEnumerable<Blog> Deger1 { get; set; }
        public IEnumerable<Blog> Deger3 { get; set; }
        public IEnumerable<Yorumlar> Deger2 { get; set; }
    }
}

TravelTripProject/Models/Sınıflar/Context.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
namespace TravelTripProject.Models.Sınıflar
{
    public class Context : DbContext
    {
        public DbSet<Admin> Admins { get; set; }
        public DbSet<AdresBlog> AdresBlogs { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Hakkında> Hakkındas { get; set; }
        public DbSet<İletisim> İletisims { get; set; }
        public DbSet<Yorumlar> Yorumlars { get; set; }
    }
}

TravelTripProject/Models/Sınıflar/Hakkında.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class Hakkında
    {
        [Key]
        public  int ID { get; set; }
        public  string FotoUrl { get; set; }
        public  string Aciklama { get; set; }
    }
}

TravelTripProject/Models/Sınıflar/Yorumlar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class Yorumlar
    {   
        [Key]
        public int ID { get; set; }
        public String KullaniciAdi { get; set; }
        public String Mail { get; set; }
        public String Yorum { get; set; }
        public int Blogid { get; set; }
        public virtual Blog Blog { get; set; }
    }
}

TravelTripProject/Models/Sınıflar/İletisim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProject.Models.Sınıflar
{
    public class İletisim
    {
        [Key]
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string Konu { get; set; }
        public string Mesaj { get; set; }
    }
}

TravelTripProject/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using TravelTripProject.Models.Sınıflar;
using Context = TravelTripProject.Models.Sınıflar.Context;


namespace TravelTripProject.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        private Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Hakkındas.ToList();
            return View(degerler);
        }
    }
}

TravelTripProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelTripProject.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

TravelTripProject/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using TravelTripProject.Models.Sınıflar;


namespace TravelTripProject.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        Context c = new Context();
        public ActionResult Index()
        {
            //var bloglar = c.Blogs.ToList();
            BlogYorum by = new BlogYorum();
            by.Deger1 = c.Blogs.ToList();
            by.Deger3 = c.Blogs.Take(3).ToList();

            return View(by);
        }

        public ActionResult BlogDetay(int id)
        {
            BlogYorum by = new BlogYorum();

            //var blogbul = c.Blogs.Where(x => x.ID == id).ToList();
            by.Deger1 = c.Blogs.Where(x => x.ID == id).ToList();
            by.Deger2 = c.Yorumlars.Where(x => x.Blogid == id).ToList();

            return View(by);
        }
    }
}

TravelTripProject/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProject.Models.Sınıflar;


namespace TravelTripProject.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        Context c = new Context();
        public ActionResult Index()
        {

            
            var degerler = c.Blogs.Take(4).ToList();
            return View(degerler);
        }
        public ActionResult About()
        {

            return View();
        }

        public PartialViewResult Partial1()
        {
            var degerler = c.Blogs.OrderByDescending(x => x.ID).Take(2).ToList();
            return PartialView(degerler);
        }
        public PartialViewResult Partial2()
        {
            var degerler = c.Blogs.Where(x => x.ID == 1).ToList();
            return PartialView(degerler);
        }
        public PartialViewResult Partial3()
        {
            var degerler = c.Blogs.ToList();
            return PartialView(degerler);
        }
    }
}

TravelTripProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelTripProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TravelTripProject/Views/About/Index.cshtml
@using TravelTripProject.Models.Sınıflar
@model List<Hakkında>
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<body>

    <div class="content">
        <div class="wrap">
            <div class="about">
                <h3>HAKKIMIZDA</h3>

                @foreach (var x in Model)
                {
                    <img src="@x.FotoUrl" alt="" />
                    <p>@x.Aciklama</p>
                }

            </div>
        </div>
    </div>

</body>
</html>

TravelTripProject/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

TravelTripProject/Views/Blog/BlogDetay.cshtml
@{
    ViewBag.Title = "BlogDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

@model TravelTripProject.Models.Sınıflar.BlogYorum





<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <!---->

</head>
<body>
    <!---header---->
    <div class="header">
        <div class="container">

            <!---start-top-nav---->

            <div class="clearfix"></div>

            <!---//End-top-nav---->
        </div>
    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
               
                    
                <div class="single-grid">
                    @foreach (var x in Model.Deger1)
                    {
                        <img src="@x.BlogImage" alt=""/>
                        <a href="">@x.Baslik</a>
                        <p>
                            @x.Aciklama
                        </p>
                    }

                </div>
                @foreach (var y in Model.Deger2)
                {
                    <ul class="comment-list">

                        <li>
                            <img src="~/web2/images/avatar.png" class="img-responsive" alt="">
                            <div class="desc">
                                <p>@y.KullaniciAdi:@y.Yorum </p>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                    </ul>
                }

                <div class="content-form">
                    <h3>Leave a comment</h3>
                    <form>
                        <input type="text" placeholder="Name" required />
                        <input type="text" placeholder="Email" required />
                        <input type="text" placeholder="Phone" required />
                        <textarea placeholder="Message"></textarea>
                        <input type="submit" value="SEND" />
                    </form>
                </div>
            </div>

          
            <div class="clearfix"></div>
        </div>
    </div>
</body>
<!---->

</html>

TravelTripProject/Views/Blog/Index.cshtml
@model  TravelTripProject.Models.Sınıflar.BlogYorum
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
   
   
    <!---->

</head>
<body>
    <!---header---->
    <div class="header">
        <div class="container">

            <!---start-top-nav---->

            <div class="clearfix"></div>

            <!---//End-top-nav---->
        </div>
    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var x in Model.Deger1)
                {
                    <div class="single-grid">
                        <img src="@x.BlogImage" alt=""/>
                        <a href="/Blog/BlogDetay/@x.ID">@x.Baslik</a>
                        <p>
                            @x.Aciklama
                        </p>

                    </div>
                }


                <div class="content-form">
                    <h3>Leave a comment</h3>
                    <form>
                        <input type="text" placeholder="Name" required/>
                        <input type="text" placeholder="Email" required/>
                        <input type="text" placeholder="Phone" required/>
                        <textarea placeholder="Message"></textarea>
                        <input type="submit" value="SEND"/>
                    </form>
                </div>
            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>Son Bloglar</h3>
                    @foreach (var y in Model.Deger3)
                    {
                        <ul>
                            <li><a href="/Blog/BlogDetay/@y.ID">@y.Baslik</a></li>

                        </ul>
                    }
                </div>
                <div class="comments">
                    <h3>Son Yorumlar</h3>
                    <ul>
                        <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                        <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                        <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                    </ul>
                </div>




            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
    <!---->

</html>

TravelTripProject/Views/Default/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<body>
  
    <div class="content">
        <div class="wrap">
            <div class="about">
                <h3>About</h3>
                <img src="~/web/images/about_banner.jpg" alt="" />
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; </p>
                <p>augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; </p>
                <p>augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>
            </div>
        </div>
    </div>
 
</body>
</html>

TravelTripProject/Views/Default/Index.cshtml
@using TravelTripProject.Models.Sınıflar
@model List<Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<body>


    <div class="header-banner">
        <div class="wrap">
            <div class="banner">
                <div class="indent">
                    <h2 class="indent-left margin-bot">HOŞ GELDİNİZ</h2>
                    <div class="banner-left">
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/glass.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Restoranlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/flight.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Uçuşlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/group.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Yapılabilecek Şeyler</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/key.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Araba Kiralama</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="header_bottom_right_images">

                        <div class="slider">
                            <ul style=" width: 600px;object-fit: cover;" class="rslides" id="slider1">
                                @foreach (var x in Model)
                                {
                                    <li><img src="@x.BlogImage" alt=""></li>

                                }

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class"content">
        <div class="wrap">
            <div class="wrapper">
                <div class="con-top">
                    <h3>GEZİ REHBERİNE HOŞGELDİNİZ</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facil</p>
                </div>
                @Html.Action("Partial1","Default")
                <div class="grids">
                    <div class="box1">
                        @Html.Action("Partial3","Default")
                        <div class="padding1">
                            <h4>Our Best Places</h4>
                            <div class="box-left">
                                <div class="bot-img">
                                    <img src="~/web/images/pic3.jpg" alt="" />
                                </div>
                                <div class="bot-desc">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="~/web/images/pic7.jpg" alt="" />
                                </div>
                                <div class="bot-desc">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="~/web/images/pic8.jpg" alt="" />
                                </div>
                                <div class="bot-desc">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="box1-left">
                                <div class="bot-img">
                                    <img src="~/web/images/pic9.jpg" alt="" />
                                </div>
                                <div class="bot-desc1">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="~/web/images/pic10.jpg" alt="" />
                                </div>
                                <div class="bot-desc1">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                                <div class="bot-img">
                                    <img src="~/web/images/pic3.jpg" alt="" />
                                </div>
                                <div class="bot-desc1">
                                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet </p>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

TravelTripProject/Views/Default/Partial1.cshtml
@using TravelTripProject.Models.Sınıflar

@model List<Blog>

<div class="con-bot">
    @foreach (var x in Model)
    {
        <div class="left">
            <div class="bot-left">
                <img src="~/web/images/pic1.jpg" alt="" />
            </div>
            <div class="left-text">
                <h4>@x.Baslik</h4>
                <span class="doller">@x.Tarih.ToString("dd.MM.yyyy")</span>

                @if (x.Aciklama.Length < 50)
                {
                    <p>
                       @x.Aciklama
                    </p>
                }
                else
                {
                    <p>  @x.Aciklama.Substring(0, 100)</p>
                }




                <p><a href="/Blog/BlogDetay/@x.ID"><span class="read">Devamını Oku>></span></a></p>
            </div>
        </div>
    }

    @Html.Action("Partial2", "Default")

    <div class="clear"></div>
</div>

TravelTripProject/Views/Default/Partial2.cshtml
@using TravelTripProject.Models.Sınıflar

@model List<Blog>

@foreach (var x in Model)
{
<div class="right">
    <div class="bot-left">
        <img src="@x.BlogImage" alt="" />
    </div>
    <div class="left-text">

        <h4>@x.Baslik</h4>
        <span class="doller">@x.Tarih.ToString("dd.MM.yyyy")</span>
        @if (x.Aciklama.Length < 50)
        {
            <p>
               @x.Aciklama
            </p>
        }
        else
        {
            <p>  @x.Aciklama.Substring(0, 80)</p>
        }
      
        <p><a href="/Blog/BlogDetay/@x.ID"><span class="read">Devamını Oku>></span></a></p>
    </div>
</div>
}
    
    

TravelTripProject/Views/Default/Partial3.cshtml
@using TravelTripProject.Models.Sınıflar
@model List<Blog>
<div class="padding">
    <h4>This Week's Top 10</h4>
    <ul class="list list-pad">
        @{int i = 0;}
       
        @foreach (var x in Model)
        {
            <li class="list-bg"><span>@{ i++;}@i .</span><a href="/Blog/BlogDetay/@x.ID">@x.Baslik</a></li>
        }


    </ul>
    <a href="#" class="link1">See all hotels</a>
</div>

TravelTripProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TravelTripProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TravelTripProject/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_AdminLayout</title>
</head>
<body>
burası Admin
<div>
    @RenderBody()
</div>
</body>
</html>

TravelTripProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giriş Sayfası", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>